# Generated by Django 5.2.5 on 2025-09-09 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedexpense',
            old_name='name',
            new_name='description',
        ),
    ]
