# Generated by Django 5.2.5 on 2025-09-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_expenses', '0002_rename_name_fixedexpense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedexpense',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
