FROM python:3.11-slim

# Configura diretório de trabalho
WORKDIR /app

# Instala dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia código do backend
COPY . .

# Expõe porta do Django
EXPOSE 8000

# Comando de execução (gunicorn ou runserver em dev)
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]