# Generated by Django 5.2.5 on 2025-09-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='account_type',
            field=models.CharField(choices=[('i', 'Receitas'), ('e', 'Despesas'), ('fe', 'Despesas Fixas')], default='i', max_length=20),
        ),
    ]
