# Generated by Django 5.2.5 on 2025-09-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_balance_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='account_type',
            field=models.CharField(choices=[('i', 'Receitas'), ('e', 'Despesas'), ('fe', 'Despesas Fixas'), ('fi', 'Receitas Fixas')], default='i', max_length=20),
        ),
    ]
